### ISSUE TITLE
Remove express view template engines from Avian?

### ISSUE THREAD

**Issue by Logikgate** [flypapertech/avian#24]
Now that avian supports any express compliant rendering engine that is added as a dependency to a user's application should we remove the few that we explicitly supported in the past from Avain's dependencies? (pug, handlebars and ejs)

This way we won't be maintaining modules that may or may not be used and each user will have full control over which version of the rendering engine they want to use since it will be in added to their project as a normal dependency.

The argument against this is that if a user wants to use, for example, pug then they need to manually run `npm -i pug --save` rather than it just working out of the box.  Not that that is a big thing to ask.

**Comment by ispyhumanfly** [comment]
After discussions with @Logikgate we will use consolidate.js as our wrapper which will support any kind of engine that it supports. So, if an app developer wants to use Pug, or hbs, or anything else, they simply install it as part of their application and we will support it out of the box.
